// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
    prompts: KVNamespace
    NEXTJS_ENV: string
    ASSETS: Fetcher
}
