#:schema node_modules/wrangler/config-schema.json
name = "cloudflare-deepseek-code-reviewer"

main = ".open-next/worker.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]

minify = true
assets = { binding = "ASSETS", directory = ".open-next/assets" }

[[kv_namespaces]]
binding = "prompts"
id = "a3c3e52d9f06410ea81e2cbf07b8ebdc"